server:
  port: 8877
spring:
  datasource:
    url: jdbc:mysql://39.107.45.29:3306/micromail?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: admin
    password: Admin1qaz!@#$
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  data:
    mongodb:
      host: 39.107.45.29
      port: 27017
      database: micromall
  redis:
    host: 39.107.45.29 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 16380 # Redis服务器连接端口
    password: AdminRedis # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
  rabbitmq:
    host: 39.107.45.29
    port: 5672
    virtual-host: tulingmall
    username: smlz
    password: smlz
    publisher-confirms: true #如果对异步消息需要回调必须设置为true
  application:
    name: tulingmall-member-demo
  cloud:
    nacos:
      discovery:
        server-addr: 39.107.45.29:8848

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-portal-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: bearer #JWT负载中拿到开头

# 自定义redis键值
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
      orderId: "portal:orderId:"
    expire:
      authCode: 90 # 验证码超期时间




