server:
  port: 8888

tuling:
  getway:
    shouldSkipUrls:
      - /oauth/**
      - /sso/**
spring:
  application:
    name: tulingmall-getway-demo
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: tulingmall-authcenter-demo
          uri: lb://tulingmall-authcenter-demo
          predicates:
            - Path=/oauth/**
    nacos:
      discovery:
        server-addr: 39.107.45.29:8848